[dependencies]

[package]
  vendor = "wander@rustpub.com"
  cjc-version = "1.0.0"
  compile-option = "-Woff unused"
  description = "AliPay Sdk for 仓颉"
  link-option = ""
  name = "alipay_sdk"
  output-type = "static"
  override-compile-option = ""
  src-dir = "src"
  target-dir = "build"
  version = "1.0.0"
  package-configuration = {}
  
[target.aarch64-apple-darwin]
  [target.aarch64-apple-darwin.bin-dependencies]
    path-option = ["${CANGJIE_STDX_HOME}/static/stdx"]

[target.x86_64-apple-darwin]
  [target.x86_64-apple-darwin.bin-dependencies]
    path-option = ["${CANGJIE_STDX_HOME}/static/stdx"]

[target.x86_64-unknown-linux-gnu]
  [target.x86_64-unknown-linux-gnu.bin-dependencies]
    path-option = ["${CANGJIE_STDX_HOME}/static/stdx"]

[target.aarch64-unknown-linux-gnu]
  [target.aarch64-unknown-linux-gnu.bin-dependencies]
    path-option = ["${CANGJIE_STDX_HOME}/static/stdx"]

[target.x86_64-linux-ohos]
  [target.x86_64-linux-ohos.bin-dependencies]
    path-option = ["${CANGJIE_STDX_HOME}/static/stdx"]

[target.aarch64-linux-ohos]
  [target.aarch64-linux-ohos.bin-dependencies]
    path-option = ["${CANGJIE_STDX_HOME}/static/stdx"]

[target.x86_64-w64-mingw32]
  [target.x86_64-w64-mingw32.bin-dependencies]
    path-option = ["${CANGJIE_STDX_HOME}/static/stdx"]