[dependencies]

[package]
  vendor = "wander@rustpub.com"
  cjc-version = "0.55.3"
  compile-option = ""
  description = "AliPay Sdk for 仓颉"
  link-option = ""
  name = "alipay_sdk_cj"
  output-type = "static"
  override-compile-option = ""
  src-dir = "src"
  target-dir = "build"
  version = "1.0.0"
  package-configuration = {}
